dist: xenial

language: python

python:
  - 3.7
  - 3.8

cache:
  pip:
  apt:
  directories:
    - .tox

env:
 - DJANGO="2.2"
 - DJANGO="3.0"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq $APT
 - sudo apt-get install gdal-bin

after_failure:
 - cat /home/travis/.pip/pip.log

after_success:
 - coveralls

install:
 - pip install pip wheel
 - pip install tox-travis
 - pip install -q coveralls flake8 tox

script:
 - env | sort
 - tox
 - flake8 --show-source --ignore C901,D203,W503 --max-line-length=100 --exclude=.tox,docs,django_comments_tree/tests,django_comments_tree/__init__.py,django_comments_tree/migrations django_comments_tree/
